remote_theme: b2a3e8/jekyll-theme-console
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jekyll-theme-console
title: wyvnzwriteupz
description: a place for me to post shit
header_pages:
- index.md
- contact.md
style: dark
footer: 'follow me on <a href="https://twitter.com/0xwyvn">twitter</a>'
