remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: wyvnzwriteupz
description: a place for me to post shit
header_pages:
- index.md
- contact.md
style: dark
footer: 'follow me on <a href="https://twitter.com/0xwyvn">twitter</a>'
