remote_theme: b2a3e8/jekyll-theme-console
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: 0xresetti
description: making blog posts malware
header_pages:
- index.md
- about.md
- buymeacoffee.md
style: dark
