remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: 0xresetti
description: making blog posts and memes about malware
header_pages:
- index.md
style: dark
